export const developers = [
  {
    name: 'Alexandr',
    surName: 'Malakhov',
    position: 'Team Lead',
    telegram: 'https://t.me/MakakhovA',
    git: 'https://github.com/Malakhow-Alexandr',
    linkedin: 'https://www.linkedin.com/in/oleksandr-malakhow/',
    avatar: require('../../../../images/developers/malakhov.jpeg'),
  },
  {
    name: 'Andrey',
    surName: 'Telnov',
    position: 'Scrum Master',
    telegram: 'https://t.me/Man_is_doc',
    git: 'https://github.com/Minaht007',
    linkedin: 'https://www.linkedin.com/in/andrey-telnov-8a968588/',
    avatar: require('../../../../images/developers/telnov.jpeg'),
  },
  {
    name: 'Oleh',
    surName: 'Buhaichuk',
    position: 'Developer',
    telegram: 'https://t.me/buga_ua',
    git: 'https://github.com/buga747',
    linkedin: 'https://www.linkedin.com/in/oleh-buhaichuk/',
    avatar: require('../../../../images/developers/buhaichuk.jpg'),
  },
  {
    name: 'Anatolii',
    surName: 'Kobzar',
    position: 'Developer',
    telegram: 'https://t.me/AnatoliiKobzar',
    git: 'https://github.com/AnatoliiKobzar',
    linkedin: 'https://www.linkedin.com/in/anatoliikobzar',
    avatar: require('../../../../images/developers/kobzar.jpg'),
  },
  {
    name: 'Oleksandr',
    surName: 'Siryi',
    position: 'Developer',
    telegram: 'https://t.me/Siryi_Oleksandr',
    git: 'https://github.com/Siryi-Oleksandr',
    linkedin: 'https://www.linkedin.com/in/oleksandr-siryi/',
    avatar: require('../../../../images/developers/siryi.jpeg'),
  },
  {
    name: 'Vladyslav',
    surName: 'Prystupa',
    position: 'Developer',
    telegram: 'https://t.me/p_vladd',
    git: 'https://github.com/VladyslavPrystupa',
    linkedin: 'https://www.linkedin.com/in/vladyslav-prystupa',
    avatar: require('../../../../images/developers/prystupa.jpeg'),
  },
  {
    name: 'Oleksandr',
    surName: 'Filippov',
    position: 'Developer',
    telegram: 'https://t.me/Filippov_Oleksandr',
    git: 'https://github.com/AlexFilp',
    linkedin: 'https://www.linkedin.com/in/oleksandr-filippov-/',
    avatar: require('../../../../images/developers/filippov.jpeg'),
  },
  {
    name: 'Yuliia',
    surName: 'Havrashenko',
    position: 'Developer',
    telegram: 'https://t.me/JuliaGavrashenko',
    git: 'https://github.com/Julia-Gavrashenko',
    linkedin: 'https://www.linkedin.com/in/yuliia-havrashenko-b02a2126a/',
    avatar: require('../../../../images/developers/havrashenko.jpeg'),
  },
  {
    name: 'Bohdan',
    surName: 'Hromchak',
    position: 'Developer',
    telegram: 'https://t.me/HromB',
    git: 'https://github.com/BohdanHromchak',
    linkedin: 'https://www.linkedin.com/in/bohdan-hromchak-21127315b',
    avatar: require('../../../../images/developers/hromchak.jpg'),
  },
  {
    name: 'Pavlo',
    surName: 'Berkut',
    position: 'Developer',
    telegram: 'https://t.me/pbDevOpen',
    git: 'https://github.com/pberkut',
    linkedin: 'https://www.linkedin.com/in/pavlo-berkut/',
    avatar: require('../../../../images/developers/berkut.jpg'),
  },
  {
    name: 'Maksym',
    surName: 'Koval',
    position: 'Developer',
    telegram: 'https://t.me/Koval_Maxim',
    git: 'https://github.com/KovalMaxim1989',
    linkedin: 'https://www.linkedin.com/in/koval-maxim/',
    avatar: require('../../../../images/developers/koval.jpg'),
  },
  {
    name: 'Nadiia',
    surName: 'Holub',
    position: 'Developer',
    telegram: 'https://t.me/NadiiaHolub',
    git: 'https://github.com/NadyaGolub',
    linkedin: 'https://www.linkedin.com/in/nadiia-holub/',
    avatar: require('../../../../images/developers/holub.jpeg'),
  },
  {
    name: 'Oleksii',
    surName: 'Savka',
    position: 'Developer',
    telegram: 'https://t.me/SavkaAleksey',
    git: 'https://github.com/Aleksey-7',
    linkedin: 'https://www.linkedin.com/in/oleksii-savka-062868269',
    avatar: require('../../../../images/developers/savka.jpg'),
  },
  {
    name: 'Dmytro',
    surName: 'Datsiuk',
    position: 'Developer',
    telegram: 'https://t.me/Dimbe',
    git: 'https://github.com/DmytroDatsiuk',
    linkedin: 'https://www.linkedin.com/in/dmytro-datsiuk-283673246/',
    avatar: require('../../../../images/developers/datsiuk.jpeg'),
  },
];
